deployment:
    name: spring-boot-deployment
    replicas: 2
    labels:
      release: helm
    podlabels: 
      release: helm
    image: abdelalidocker/nginx-k8s
    containername: spring-boot-container
    containerport: 8080
    resources: 
        requests:
             memory: "128Mi"
             cpu: "100m"
        limits:
            memory: "500Mi"
            cpu: "200m"

service:
    name: helm-service
    labels: 
       release: helm
    type: NodePort
    port: 80
    targetPort: 8080
    nodePort: 30080